apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-cache-vol
  labels:
    type: local
spec:
  storageClassName: image-cache-vol
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: ## This is only required for local, it defines which nodes can access it
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
