apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: todo-backend
          image: docker.io/iku1/todo_backend:2.2
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5005"
