apiVersion: v1
kind: Pod
metadata:
  name: curlpod
  labels:
    app: curlpod
spec:
  containers:
  - image: curlimages/curl:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curl
  restartPolicy: Always