apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: docker.io/iku1/ping_pong:1.9