apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-volume-claim
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: ping-pong
          image: docker.io/iku1/ping_pong:2.1
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-logs
            mountPath: /tmp/pong_log
          env:
            - name: LOG_FILE
              value: /tmp/pong_log/pong_count
            - name: PORT
              value: "5001"
