apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-volume-claim
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: log-writer
          image: docker.io/iku1/log_output_writer:1.11
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-logs
            mountPath: /tmp/log_output
          env:
            - name: LOG_FILE_PATH
              value: "/tmp/log_output/random.log"
        - name: log-reader-api
          image: docker.io/iku1/log_output_reader_api:2.1
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-logs
            mountPath: /tmp/log_output
          env:
            - name: LOG_FILE_PATH
              value: "/tmp/log_output/random.log"
            - name: PONG_COUNT_SERVICE_URL
              value: "http://ping-pong-svc:5001/pings"
            - name: PORT
              value: "5000"
