apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-writer
          image: docker.io/iku1/log_output_writer:1.10
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-logs
            mountPath: /tmp/log_output
          env:
            - name: LOG_FILE_PATH
              value: "/tmp/log_output/random.log"
        - name: log-reader-api
          image: docker.io/iku1/log_output_reader_api:1.10
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-logs
            mountPath: /tmp/log_output
          env:
            - name: LOG_FILE_PATH
              value: "/tmp/log_output/random.log"
            - name: PORT
              value: "5000"